version: "3.7"
networks:
  default:
    internal: true
services:
  homarus:
    image: ${REPOSITORY:-islandora}/homarus:${TAG:-latest}
    environment:
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-60}
  houdini:
    image: ${REPOSITORY:-islandora}/houdini:${TAG:-latest}
  hypercube:
    image: ${REPOSITORY:-islandora}/hypercube:${TAG:-latest}
